DATA_RETURNS = "returns"
DATA_REWARDS = "rewards"
DATA_OBSERVATIONS = "observations"
DATA_ACTIONS = "actions"
DATA_PARAMETERS = "parameters"
DATA_TERMINALS = "dones"
DATA_LAST_OBSERVATIONS = "last_observations"

DATA_EXPLORATION_RETURNS = "exploration_returns"
DATA_EXPLORATION_REWARDS = "exploration_rewards"
DATA_EVALUATION_RETURNS = "evaluation_returns"

LOG_TAG_CRITIC_LOSS = "critic_loss"
LOG_TAG_ACTOR_LOSS = "actor_loss"
LOG_ACTOR_STEP_PENALTY_LOSS = "actor_step_penalty_loss"

FILE_ACTOR_STATE_DICT = "actor_state_dict"
FILE_CRITIC_STATE_DICT = "critic_state_dict"
FILE_ACTOR_OPTIMIZER_STATE_DICT = "actor_optimizer_state_dict"
FILE_CRITIC_OPTIMIZER_STATE_DICT = "critic_optimizer_state_dict"
FILE_TRAINER_STEP_COUNT = "num_train_steps"
FILE_REPLAY_BUFFER = "replay_buffer.npz"
FILE_REPLAY_BUFFER_PREFIX = "replay_buffer_"
FILE_REDUNDANCY_REPLAY_BUFFER = "redundancy_buffer.npz"

ARGS_CRITIC = "critic"
ARGS_ACTOR = "actor"
ARGS_CRITIC_OPTIMIZER = "critic_optimizer"
ARGS_ACTOR_OPTIMIZER = "actor_optimizer"
ARGS_ACTOR_TARGET_NET = "actor_target_net"
ARGS_CRITIC_TARGET_NET = "critic_target_net"
ARGS_CRITIC_2 = "critic_2"
ARGS_CRITIC_2_OPTIMIZER = "critic_2_optimizer"
ARGS_CRITIC_TARGET_NET_2 = "critic_target_net_2"
